In [3]:
import numpy as np

arr = np.array([1, 2,3])
print(type(arr))

<class 'numpy.ndarray'>


In [13]:
zeroes_arr = np.zeros((2,3))
print(zeroes_arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [14]:
arange_arr = np.arange(0, 10, 2)
print(arange_arr)

[0 2 4 6 8]


In [9]:
linspace_arr = np.linspace(0,5,5)
linspace_arr

array([0.  , 1.25, 2.5 , 3.75, 5.  ])

In [27]:
random_arr = np.random.rand(2, 3)*9+1
print(random_arr)
random_arr1 = np.random.randint(low =2, high = 25,size=(2,3))
print(random_arr1)

[[6.46868137 2.3835076  2.30305284]
 [3.34063204 5.68973053 2.54332226]]
[[22 21 20]
 [15 18 15]]


In [31]:
arr = np.random.randint(low= 2, high = 10, size= (3,3))
print(arr)
print(arr[2,2])


[[5 9 5]
 [3 8 9]
 [4 7 3]]
3


In [33]:
arr = 0, 1, 2
print(arr)
array_1 = np.array([0,2,5])
print(array_1)

(0, 1, 2)
[0 2 5]


In [34]:
arr = np.array([0,1,2,3,5,6,])
new_arr = arr.reshape(2,3)
print(new_arr)

[[0 1 2]
 [3 5 6]]


In [37]:
arr = np.array([0,1,2,3,5,6,10,9,7,25,56,36])
new_arr = arr.reshape(2,3,2)
print(new_arr)

[[[ 0  1]
  [ 2  3]
  [ 5  6]]

 [[10  9]
  [ 7 25]
  [56 36]]]
